server:
  port: 8085
  servlet:
    context-path: /monitor
  tomcat:
    uri-encoding: utf-8
spring:
  application:
    name: system
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
    name: monitor
    url: jdbc:mysql://10.184.33.111/monitor?useUnicode=true&useTimezone=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&autoReconnect=true&serverTimezone=UTC
    username: root
    password: MoZongChang0712_yksy
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
  devtools:
    restart:
      enabled: true

  #配置使用模板
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    cache: false #关闭缓存
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    servlet:
      content-type: text/html

  mvc:
    view:
      prefix: /
      suffix: .html
      static-path-pattern: /static/**

  #redis配置
    redis:
      host: 10.184.33.111
      port: 6379
      password: MoZongChang0712_redis
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 100000
      timeout: 0

  # 配置静态资源文件路径
  resources:
    #    static-locations: ["/templates/","/resources/","/static/","/public/"]
    #指定静态资源路径，默认为classpath:[/META-INF/resources/,/resources/, /static/, /public/]以及context:/
    static-locations: classpath:/templates,classpath:/META-INF/resources,classpath:/resources,classpath:/static,classpath:/public
  #json格式化配置
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
#    serialization: false

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#配置持久层mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath*:mapper/*.xml,classpath*:mapper/plan/*.xml,classpath*:mapper/data/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.petrochina.e7.monitor.dao  # 注意：对应实体类的路径com.petrochina.e7.monitor.dao
  #  config-location: classpath:mybatis/mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true #配置驼峰命

#配置日志,日志生成在当前项目下project.log
logging:
  config: classpath:config/Log4j2.xml #配置加载日志配置文件
  path: develop/mzc/monitorLog/project/project.log #配置日志文件路径
  level:
    root: info
    com.petrochina.e7.monitor.project: trace
    com.petrochina.e7.monitor.decard: trace
    com.petrochina.e7.monitor.dao: debug
#  file作用同path作用类似,使用系统默认就可以
#  file: project.log
#  level: trace
#在当前磁盘的根路径下创建spring文件夹和里面的log文件夹；使用 project.log 作为默认文件
#  path: /monitor/log/project.log
#  pattern:
#    console: %d{yyyy‐MM‐dd} [%thread] %‐5level %logger{50} ‐ %msg%n
#    file: %d{yyyy‐MM‐dd} === [%thread] === %‐5level === %logger{50} ==== %msg%n
